#logging 설정
server:
  port: 8089
logging:
  level:
    org.springframework: DEBUG
    org.springframework.web: DEBUG
#socket.io 설정
socketio:
  host: 192.168.0.23
  port: 9001
  # Set the maximum length of processing data per frame to prevent others from using large data to attack the server
  maxFramePayloadLength: 1048576
  # Set maximum content length for http interaction
  maxHttpContentLength: 1048576
  # Size of socket connections (e.g., listening on only one port box thread group is 1)
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # Protocol upgrade timeout (milliseconds), default 10 seconds.HTTP handshake upgrade to ws protocol timeout
  upgradeTimeout: 1000000
  # Ping message timeout (milliseconds), default 60 seconds, within which a timeout event is sent if no heartbeat message is received
  pingTimeout: 6000000
  # Ping message interval (milliseconds), default 25 seconds.Client sends a heartbeat message interval to server
  pingInterval: 25000
  ssl:
    cert-name: File_www.xne20bw05b.kr_apache.crt
    key-name: KeyFile_www.xne20bw05b.kr_apache.pem
    jks-name: www.xne20bw05b.kr.jks